import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/toaster";
import AuthContextProvider from "../context/auth-context-provider";
import MailPage from "./dashboard/page";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get("token");

  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <AuthContextProvider>
          {!!token ? (
            <>
              <MailPage>{children}</MailPage>
            </>
          ) : (
            <>{children}</>
          )}
          <Toaster />
        </AuthContextProvider>
      </body>
    </html>
  );
}
